#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

MODEL_IMPL="${MODEL_IMPL:-retina}" \
BACKBONE="${BACKBONE:-resnet50}" \
WANDB_RUN_NAME="${WANDB_RUN_NAME:-retina-50-512x768}" \
MIN_SIZE="${MIN_SIZE:-512}" \
MAX_SIZE="${MAX_SIZE:-768}" \
PRETRAINED_BACKBONE="${PRETRAINED_BACKBONE:-1}" \
TRAINABLE_BACKBONE_LAYERS="${TRAINABLE_BACKBONE_LAYERS:-3}" \
SCORE_THRESHOLD="${SCORE_THRESHOLD:-0.05}" \
NMS_THRESHOLD="${NMS_THRESHOLD:-0.4}" \
RETINA_TOPK_CANDIDATES="${RETINA_TOPK_CANDIDATES:-2000}" \
RETINA_MAX_DETECTIONS="${RETINA_MAX_DETECTIONS:-300}" \
SAMPLER_STRATEGY="${SAMPLER_STRATEGY:-none}" \
AUGMENTATION="${AUGMENTATION:-0}" \
HORIZONTAL_FLIP_PROBABILITY=0.5 \
COLOR_JITTER_PROBABILITY=0.3 \
GRAYSCALE_PROBABILITY=0.03 \
SCALE_JITTER_PROBABILITY=0.4 \
SCALE_JITTER_MIN=0.85 \
SCALE_JITTER_MAX=1.20 \
SAFE_CROP_PROBABILITY=0.1 \
SAFE_CROP_MIN_SCALE=0.8 \
SAFE_CROP_MIN_VISIBILITY=0.7 \
BLUR_PROBABILITY=0.0 \
NOISE_PROBABILITY=0.0 \
EPOCHS="${EPOCHS:-100}" \
BATCH_SIZE="${BATCH_SIZE:-4}" \
NUM_WORKERS="${NUM_WORKERS:-4}" \
LR_SCHEDULER="${LR_SCHEDULER:-cosine}" \
USE_WANDB="${USE_WANDB:-1}" \
GPU="${GPU:-0}" \
bash script.sh train