#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

MODEL_IMPL="${MODEL_IMPL:-retina}" \
BACKBONE="${BACKBONE:-hgnetv2_b4}" \
WANDB_RUN_NAME="${WANDB_RUN_NAME:-retina-hgnetv2-b4-fpn}" \
MIN_SIZE="${MIN_SIZE:-512}" \
MAX_SIZE="${MAX_SIZE:-768}" \
PRETRAINED_BACKBONE="${PRETRAINED_BACKBONE:-1}" \
TRAINABLE_BACKBONE_LAYERS="${TRAINABLE_BACKBONE_LAYERS:-2}" \
SCORE_THRESHOLD="${SCORE_THRESHOLD:-0.05}" \
NMS_THRESHOLD="${NMS_THRESHOLD:-0.5}" \
RETINA_TOPK_CANDIDATES="${RETINA_TOPK_CANDIDATES:-2000}" \
RETINA_MAX_DETECTIONS="${RETINA_MAX_DETECTIONS:-300}" \
SAMPLER_STRATEGY="${SAMPLER_STRATEGY:-class_small_balanced}" \
AUGMENTATION="${AUGMENTATION:-1}" \
USE_WANDB="${USE_WANDB:-1}" \
GPU="${GPU:-0}" \
bash script.sh train
